// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtwbuUerf9OCAzqJL37k4FLLoEKdbGThU',
    appId: '1:1011733861517:web:5b3ae365238c375039fec4',
    messagingSenderId: '1011733861517',
    projectId: 'book-store-app-66820',
    authDomain: 'book-store-app-66820.firebaseapp.com',
    databaseURL: 'https://book-store-app-66820-default-rtdb.firebaseio.com',
    storageBucket: 'book-store-app-66820.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2VH5sS0L9LG_kDkgDQ7a8Vo2fQQWyZks',
    appId: '1:1011733861517:android:d0a53a1235263fb239fec4',
    messagingSenderId: '1011733861517',
    projectId: 'book-store-app-66820',
    databaseURL: 'https://book-store-app-66820-default-rtdb.firebaseio.com',
    storageBucket: 'book-store-app-66820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD--7DW4L0TOj31-20q5llh78BLMuK3tUE',
    appId: '1:1011733861517:ios:a0cfc900dddca26639fec4',
    messagingSenderId: '1011733861517',
    projectId: 'book-store-app-66820',
    databaseURL: 'https://book-store-app-66820-default-rtdb.firebaseio.com',
    storageBucket: 'book-store-app-66820.firebasestorage.app',
    iosBundleId: 'com.example.ungdungbansach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD--7DW4L0TOj31-20q5llh78BLMuK3tUE',
    appId: '1:1011733861517:ios:a0cfc900dddca26639fec4',
    messagingSenderId: '1011733861517',
    projectId: 'book-store-app-66820',
    databaseURL: 'https://book-store-app-66820-default-rtdb.firebaseio.com',
    storageBucket: 'book-store-app-66820.firebasestorage.app',
    iosBundleId: 'com.example.ungdungbansach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtwbuUerf9OCAzqJL37k4FLLoEKdbGThU',
    appId: '1:1011733861517:web:861274153eb276a239fec4',
    messagingSenderId: '1011733861517',
    projectId: 'book-store-app-66820',
    authDomain: 'book-store-app-66820.firebaseapp.com',
    databaseURL: 'https://book-store-app-66820-default-rtdb.firebaseio.com',
    storageBucket: 'book-store-app-66820.firebasestorage.app',
  );
}
